# Generated by Django 4.2.7 on 2026-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Açıklama ve yorum (cevap verildikten sonra gösterilir)'),
        ),
    ]
